# Create a Pipeline

You can perform the various steps required to ingest data, train a model, and register the model individually by using the Azure ML SDK to run script-based experiments. However, in an enterprise environment it is common to encapsulate the sequence of discrete steps required to build a machine learning solution into a *pipeline* that can be run on one or more compute targets, either on-demand by a user, from an automated build process, or on a schedule.

In this notebook, you'll bring together all of these elements to create a simple pipeline that pre-processes data and then trains and registers a model.

## Install the Azure Machine Learning SDK

The Azure Machine Learning SDK is updated frequently. Run the following cell to upgrade to the latest release, along with the additional package to support notebook widgets.

In [ ]:
!pip install --upgrade azureml-sdk azureml-widgets

## Connect to your workspace

With the latest version of the SDK installed, now you're ready to connect to your workspace.

> **Note**: If you haven't already established an authenticated session with your Azure subscription, you'll be prompted to authenticate by clicking a link, entering an authentication code, and signing into Azure.

In [24]:
import azureml.core
from azureml.core import Workspace

# Load the workspace from the saved config file
ws = Workspace.from_config()
print('Ready to use Azure ML {} to work with {}'.format(azureml.core.VERSION, ws.name))

Ready to use Azure ML 1.19.0 to work with cloudnativeml


## Prepare data

In your pipeline, you'll use a dataset containing details of diabetes patients. Run the cell below to create this dataset (if you created it in previously, the code will find the existing version)

In [17]:
from azureml.core import Dataset

default_ds = ws.get_default_datastore()

dataset_name = 'fashion_mnist_ds'

# Get a dataset by name
fashion_mnist_raw = Dataset.get_by_name(workspace=ws, name=dataset_name)
print(fashion_mnist_raw)

FileDataset
{
  "source": [
    "('workspaceblobstore', 'fashion_mnist_data')"
  ],
  "definition": [
    "GetDatastoreFiles"
  ],
  "registration": {
    "id": "1fa1d763-fcd2-464b-a59a-0779a32539fc",
    "name": "fashion_mnist_ds",
    "version": 1,
    "description": "fashion_mnist training data",
    "workspace": "Workspace.create(name='cloudnativeml', subscription_id='a2a1fc9f-5671-4479-8922-ad16e34c0fdc', resource_group='cloud-native-ml')"
  }
}


## Create scripts for pipeline steps

Pipelines consist of one or more *steps*, which can be Python scripts, or specialized steps like a data transfer step that copies data from one location to another. Each step can run in its own compute context. In this exercise, you'll build a simple pipeline that contains two Python script steps: one to pre-process some training data, and another to use the pre-processed data to train and register a model.

First, let's create a folder for the script files we'll use in the pipeline steps.

In [25]:
import os
# Create a folder for the pipeline step files
experiment_folder = 'fashion_mnist_pipeline'
os.makedirs(experiment_folder, exist_ok=True)

print(experiment_folder)

fashion_mnist_pipeline


Now let's create the first script, which will read data from the diabetes dataset and apply some simple pre-processing to remove any rows with missing data and normalize the numeric features so they're on a similar scale.

The script includes a argument named **--prepped-data**, which references the folder where the resulting data should be saved.

Now you can create the script for the second step, which will train a model. The script includes a argument named **--training-folder**, which references the folder where the prepared data was saved by the previous step.

## Prepare a compute environment for the pipeline steps

In this exercise, you'll use the same compute for both steps, but it's important to realize that each step is run independently; so you could specify different compute contexts for each step if appropriate.

First, get the compute target you created in a previous lab (if it doesn't exist, it will be created).

> **Important**: Change *your-compute-cluster* to the name of your compute cluster in the code below before running it! Cluster names must be globally unique names between 2 to 16 characters in length. Valid characters are letters, digits, and the - character.

In [26]:
from azureml.core.compute import ComputeTarget, AmlCompute
from azureml.core.compute_target import ComputeTargetException

cluster_name = "larger-cluster"

try:
    # Check for existing compute target
    pipeline_cluster = ComputeTarget(workspace=ws, name=cluster_name)
    print('Found existing cluster, use it.')
except ComputeTargetException:
    # If it doesn't already exist, create it
    try:
        compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_DS11_V2', max_nodes=2)
        pipeline_cluster = ComputeTarget.create(ws, cluster_name, compute_config)
        pipeline_cluster.wait_for_completion(show_output=True)
    except Exception as ex:
        print(ex)
    

Found existing cluster, use it.


The compute will require a Python environment with the necessary package dependencies installed, so you'll need to create a run configuration.

In [27]:
from azureml.core import Environment
from azureml.core.conda_dependencies import CondaDependencies
from azureml.core.runconfig import RunConfiguration

registered_env = Environment.get(ws, 'fashionenv')

# Create a new runconfig object for the pipeline
pipeline_run_config = RunConfiguration()

# Use the compute you created above. 
pipeline_run_config.target = pipeline_cluster

# Assign the environment to the run configuration
pipeline_run_config.environment = registered_env

print ("Run configuration created.")

Run configuration created.


## Create and run a pipeline

Now you're ready to create and run a pipeline.

First you need to define the steps for the pipeline, and any data references that need to passed between them. In this case, the first step must write the prepared data to a folder that can be read from by the second step. Since the steps will be run on remote compute (and in fact, could each be run on different compute), the folder path must be passed as a data reference to a location in a datastore within the workspace. The **PipelineData** object is a special kind of data reference that is used for interim storage locations that can be passed between pipeline steps, so you'll create one and use at as the output for the first step and the input for the second step. Note that you also need to pass it as a script argument so our code can access the datastore location referenced by the data reference.

In [28]:
from azureml.pipeline.core import PipelineData
from azureml.pipeline.steps import PythonScriptStep

# Get the training dataset
fashion_mnist_ds = ws.datasets.get("fashion_mnist_ds")

# Create a PipelineData (temporary Data Reference) for the model folder
prepped_data_folder = PipelineData("prepped_data_folder", datastore=ws.get_default_datastore())

# Step 1, Run the data prep script
prep_step = PythonScriptStep(name = "Prepare Data",
                                source_directory = experiment_folder,
                                script_name = "prep_fashion_mnist.py",
                                arguments = ['--prepped-data', prepped_data_folder],
                                outputs=[prepped_data_folder],
                                compute_target = cluster_name,
                                runconfig = pipeline_run_config,
                                allow_reuse = True)

# Step 2, run the training script
train_step = PythonScriptStep(name = "Train Model",
                                source_directory = experiment_folder,
                                script_name = "train_fashion_mnist.py",
                                arguments = ['--training-folder', prepped_data_folder],
                                inputs=[prepped_data_folder],
                                compute_target = cluster_name,
                                runconfig = pipeline_run_config,
                                allow_reuse = True)

print("Pipeline steps defined")

Pipeline steps defined


OK, you're ready build the pipeline from the steps you've defined and run it as an experiment.

In [29]:
from azureml.core import Experiment
from azureml.pipeline.core import Pipeline
from azureml.widgets import RunDetails

# Construct the pipeline
pipeline_steps = [prep_step, train_step]
pipeline = Pipeline(workspace=ws, steps=pipeline_steps)
print("Pipeline is built.")

# Create an experiment and run the pipeline
experiment = Experiment(workspace=ws, name = 'fashion-mnist-pipeline')
pipeline_run = experiment.submit(pipeline, regenerate_outputs=True)
print("Pipeline submitted for execution.")
RunDetails(pipeline_run).show()
pipeline_run.wait_for_completion(show_output=True)

Pipeline is built.
Created step Prepare Data [62560ec1][3db3fc96-2cb9-40ab-a039-63e289981041], (This step will run and generate new outputs)
Created step Train Model [8ac270d9][f4f80de9-16ae-4ee4-9339-fd4844a4ad40], (This step will run and generate new outputs)
Submitted PipelineRun a3f005d0-e7eb-4d73-a276-26f885e1b9ae
Link to Azure Machine Learning Portal: https://ml.azure.com/experiments/fashion-mnist-pipeline/runs/a3f005d0-e7eb-4d73-a276-26f885e1b9ae?wsid=/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourcegroups/cloud-native-ml/workspaces/cloudnativeml
Pipeline submitted for execution.


_PipelineWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO', …

PipelineRunId: a3f005d0-e7eb-4d73-a276-26f885e1b9ae
Link to Azure Machine Learning Portal: https://ml.azure.com/experiments/fashion-mnist-pipeline/runs/a3f005d0-e7eb-4d73-a276-26f885e1b9ae?wsid=/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourcegroups/cloud-native-ml/workspaces/cloudnativeml
PipelineRun Status: NotStarted
PipelineRun Status: Running


StepRunId: f3c995c8-bc6e-40f2-84a6-0e48a8948446
Link to Azure Machine Learning Portal: https://ml.azure.com/experiments/fashion-mnist-pipeline/runs/f3c995c8-bc6e-40f2-84a6-0e48a8948446?wsid=/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourcegroups/cloud-native-ml/workspaces/cloudnativeml
StepRun( Prepare Data ) Status: NotStarted
StepRun( Prepare Data ) Status: Running

Streaming azureml-logs/55_azureml-execution-tvmps_c09b1405b81708967ccf2c69e51e0121bcac97c6ec745379ffba66765e016c6b_p.txt
2021-01-05T14:51:35Z Starting output-watcher...
2021-01-05T14:51:35Z IsDedicatedCompute == False, starting polling for Low-Pri Preempt


Streaming azureml-logs/70_driver_log.txt
2021/01/05 14:51:48 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/info
2021/01/05 14:51:48 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
[2021-01-05T14:51:50.457315] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError', 'UserExceptions:context_managers.UserExceptions'], invocation=['prep_fashion_mnist.py', '--prepped-data', '/mnt/batch/tasks/shared/LS_root/jobs/cloudnativeml/azureml/f3c995c8-bc6e-40f2-84a6-0e48a8948446/mounts/workspaceblobstore/azureml/f3c995c8-bc6e-40f2-84a6-0e48a8948446/prepped_data_folder'])
Script type = None
Starting the daemon thread to refresh tokens in background for process with pid = 113
Entering Run History Context Manager.
[2021-01-05T14:51:54.627152] Current directory: 




StepRunId: 97458488-4ec2-4aa8-9bff-98f28a9b41cf
Link to Azure Machine Learning Portal: https://ml.azure.com/experiments/fashion-mnist-pipeline/runs/97458488-4ec2-4aa8-9bff-98f28a9b41cf?wsid=/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourcegroups/cloud-native-ml/workspaces/cloudnativeml
StepRun( Train Model ) Status: NotStarted
StepRun( Train Model ) Status: Running

Streaming azureml-logs/55_azureml-execution-tvmps_c09b1405b81708967ccf2c69e51e0121bcac97c6ec745379ffba66765e016c6b_p.txt
2021-01-05T14:52:57Z Starting output-watcher...
2021-01-05T14:52:57Z IsDedicatedCompute == False, starting polling for Low-Pri Preemption
2021-01-05T14:52:58Z Executing 'Copy ACR Details file' on 10.0.0.4
2021-01-05T14:52:58Z Copy ACR Details file succeeded on 10.0.0.4. Output: 
>>>   
>>>   
Login Succeeded
Using default tag: latest
latest: Pulling from azureml/azureml_4fcb7f9f1e1fe37e2aae422251b001cb
Digest: sha256:70909e987b487be7c09bff94cd21cc4be13da57effbd82f77a8e7d1c1dc063c2
Status: Im


Streaming azureml-logs/70_driver_log.txt
2021/01/05 14:53:07 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/info
2021/01/05 14:53:07 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
[2021-01-05T14:53:10.175858] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError', 'UserExceptions:context_managers.UserExceptions'], invocation=['train_fashion_mnist.py', '--training-folder', '/mnt/batch/tasks/shared/LS_root/jobs/cloudnativeml/azureml/97458488-4ec2-4aa8-9bff-98f28a9b41cf/mounts/workspaceblobstore/azureml/f3c995c8-bc6e-40f2-84a6-0e48a8948446/prepped_data_folder'])
Script type = None
Starting the daemon thread to refresh tokens in background for process with pid = 113
Entering Run History Context Manager.
[2021-01-05T14:53:14.201353] Current directo

25984/60000 [===========>..................] - ETA: 26s - loss: 0.8366 - accuracy: 0.6850


46464/60000 [======================>.......] - ETA: 10s - loss: 0.7065 - accuracy: 0.7361


60000/60000 [==============================] - 47s 786us/sample - loss: 0.6588 - accuracy: 0.7551 - val_loss: 0.4415 - val_accuracy: 0.8356
Epoch 2/10

 4480/60000 [=>............................] - ETA: 41s - loss: 0.4681 - accuracy: 0.8324


26112/60000 [============>.................] - ETA: 23s - loss: 0.4595 - accuracy: 0.8357


48640/60000 [=======================>......] - ETA: 7s - loss: 0.4443 - accuracy: 0.8403


60000/60000 [==============================] - 44s 727us/sample - loss: 0.4386 - accuracy: 0.8422 - val_loss: 0.3599 - val_accuracy: 0.8667
Epoch 3/10

 6784/60000 [==>...........................] - ETA: 37s - loss: 0.4120 - accuracy: 0.8496


27008/60000 [============>.................] - ETA: 24s - loss: 0.3943 - accuracy: 0.8546


46848/60000 [======================>.......] - ETA: 9s - loss: 0.3901 - accuracy: 0.8571


60000/60000 [==============================] - 47s 786us/sample - loss: 0.3879 - accuracy: 0.8586 - val_loss: 0.3269 - val_accuracy: 0.8783
Epoch 4/10

 3712/60000 [>.............................] - ETA: 41s - loss: 0.3657 - accuracy: 0.8680


24576/60000 [===========>..................] - ETA: 25s - loss: 0.3613 - accuracy: 0.8682


44800/60000 [=====================>........] - ETA: 11s - loss: 0.3619 - accuracy: 0.8689


60000/60000 [==============================] - 46s 761us/sample - loss: 0.3599 - accuracy: 0.8694 - val_loss: 0.3101 - val_accuracy: 0.8855
Epoch 5/10

 3200/60000 [>.............................] - ETA: 38s - loss: 0.3186 - accuracy: 0.8859


24704/60000 [===========>..................] - ETA: 24s - loss: 0.3426 - accuracy: 0.8753


45696/60000 [=====================>........] - ETA: 10s - loss: 0.3374 - accuracy: 0.8765


60000/60000 [==============================] - 44s 732us/sample - loss: 0.3366 - accuracy: 0.8764 - val_loss: 0.2928 - val_accuracy: 0.8938
Epoch 6/10

 4992/60000 [=>............................] - ETA: 36s - loss: 0.3288 - accuracy: 0.8802


25984/60000 [===========>..................] - ETA: 23s - loss: 0.3203 - accuracy: 0.8811


46848/60000 [======================>.......] - ETA: 9s - loss: 0.3202 - accuracy: 0.8822


60000/60000 [==============================] - 45s 745us/sample - loss: 0.3189 - accuracy: 0.8835 - val_loss: 0.2768 - val_accuracy: 0.8998
Epoch 7/10

 5120/60000 [=>............................] - ETA: 39s - loss: 0.3210 - accuracy: 0.8814


27264/60000 [============>.................] - ETA: 22s - loss: 0.3028 - accuracy: 0.8869


47872/60000 [======================>.......] - ETA: 8s - loss: 0.3102 - accuracy: 0.8857


60000/60000 [==============================] - 44s 739us/sample - loss: 0.3074 - accuracy: 0.8869 - val_loss: 0.2758 - val_accuracy: 0.8985
Epoch 8/10

 5760/60000 [=>............................] - ETA: 40s - loss: 0.3010 - accuracy: 0.8918


28288/60000 [=============>................] - ETA: 21s - loss: 0.2989 - accuracy: 0.8926


49280/60000 [=======================>......] - ETA: 7s - loss: 0.2966 - accuracy: 0.8917


60000/60000 [==============================] - 44s 731us/sample - loss: 0.2952 - accuracy: 0.8921 - val_loss: 0.2687 - val_accuracy: 0.9012
Epoch 9/10

 7424/60000 [==>...........................] - ETA: 38s - loss: 0.2854 - accuracy: 0.8935


28288/60000 [=============>................] - ETA: 22s - loss: 0.2816 - accuracy: 0.8953


49664/60000 [=======================>......] - ETA: 7s - loss: 0.2833 - accuracy: 0.8949


60000/60000 [==============================] - 46s 761us/sample - loss: 0.2850 - accuracy: 0.8950 - val_loss: 0.2573 - val_accuracy: 0.9051
Epoch 10/10

 6272/60000 [==>...........................] - ETA: 41s - loss: 0.2660 - accuracy: 0.9077


26240/60000 [============>.................] - ETA: 25s - loss: 0.2793 - accuracy: 0.8982


46592/60000 [======================>.......] - ETA: 10s - loss: 0.2772 - accuracy: 0.8980


60000/60000 [==============================] - 47s 777us/sample - loss: 0.2768 - accuracy: 0.8978 - val_loss: 0.2554 - val_accuracy: 0.9074
Test Loss:  0.25535974576473236
Test Accuracy:  0.9074
Time to run:  452.80747175216675


(10000, 10)
['Top', 'Trouser', 'Jumper', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Trainer', 'Bag', 'Ankle boot']
[[892   0  13  23   2   1  65   0   4   0]
 [  0 976   0  19   2   0   1   0   2   0]
 [ 20   1 888  10  31   0  50   0   0   0]
 [ 12   3   8 927  24   0  25   0   1   0]
 [  2   0  99  27 786   0  85   0   1   0]
 [  0   0   0   0   0 988   0  10   0   2]
 [122   1  76  30  59   0 707   0   5   0]
 [  0   0   0   0   0   9   0 978   0  13]
 [  2   1   2   5   2   3   2   3 980   0]
 [  0   0   0   0   0   5   1  42   0 952]]
Saving model...
Registering model...
Registering model fashion_mnist_model
Starting the daemon thread to refresh tokens in background for process with pid = 113


[2021-01-05T15:01:05.997111] The experiment completed successfully. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
2 items cleaning up...
Cleanup took 0.14736342430114746 seconds
[2021-01-05T15:01:06.583599] Finished context manager injector.
2021/01/05 15:01:



PipelineRun Execution Summary
PipelineRun Status: Finished
{'runId': 'a3f005d0-e7eb-4d73-a276-26f885e1b9ae', 'status': 'Completed', 'startTimeUtc': '2021-01-05T14:50:50.224894Z', 'endTimeUtc': '2021-01-05T15:01:49.029366Z', 'properties': {'azureml.runsource': 'azureml.PipelineRun', 'runSource': 'SDK', 'runType': 'SDK', 'azureml.parameters': '{}'}, 'inputDatasets': [], 'outputDatasets': [], 'logFiles': {'logs/azureml/executionlogs.txt': 'https://cloudnativeml8223825908.blob.core.windows.net/azureml/ExperimentRun/dcid.a3f005d0-e7eb-4d73-a276-26f885e1b9ae/logs/azureml/executionlogs.txt?sv=2019-02-02&sr=b&sig=d7Sg0ShJwySbH9mSjcqAz8DebabdlpirhiPEfbaZoPo%3D&st=2021-01-05T14%3A41%3A09Z&se=2021-01-05T22%3A51%3A09Z&sp=r', 'logs/azureml/stderrlogs.txt': 'https://cloudnativeml8223825908.blob.core.windows.net/azureml/ExperimentRun/dcid.a3f005d0-e7eb-4d73-a276-26f885e1b9ae/logs/azureml/stderrlogs.txt?sv=2019-02-02&sr=b&sig=YRBS224NgUQ9UDvVugWrg10%2BE4bUg5lZCWmHU%2BsDjBs%3D&st=2021-01-05T14%3A41%3

'Finished'

A graphical representation of the pipeline experiment will be displayed in the widget as it runs. keep an eye on the kernel indicator at the top right of the page, when it turns from **&#9899;** to **&#9711;**, the code has finished running. You can also monitor pipeline runs in the **Experiments** page in [Azure Machine Learning studio](https://ml.azure.com).

When the pipeline has finished, you can examine the metrics recorded by it's child runs.

In [30]:
for run in pipeline_run.get_children():
    print(run.name, ':')
    metrics = run.get_metrics()
    for metric_name in metrics:
        print('\t',metric_name, ":", metrics[metric_name])

Train Model :
	 training-set-dim : (60000, 28, 28, 1)
	 test-set-dim : (10000, 28, 28, 1)
	 Test Loss:  : 0.25535974576473236
	 Test Accuracy:  : 0.9074000120162964
	 Time to run:  : 452.80747175216675
	 TrainingVsValidationAccuracy : aml://artifactId/ExperimentRun/dcid.97458488-4ec2-4aa8-9bff-98f28a9b41cf/TrainingVsValidationAccuracy_1609858857.png
	 TrainingVsValidationLoss : aml://artifactId/ExperimentRun/dcid.97458488-4ec2-4aa8-9bff-98f28a9b41cf/TrainingVsValidationLoss_1609858857.png
	 TestData : aml://artifactId/ExperimentRun/dcid.97458488-4ec2-4aa8-9bff-98f28a9b41cf/TestData_1609858860.png
	 CorrelationMatrix : aml://artifactId/ExperimentRun/dcid.97458488-4ec2-4aa8-9bff-98f28a9b41cf/CorrelationMatrix_1609858863.png
Prepare Data :
	 training-set-dim : (60000, 28, 28)
	 test-set-dim : (10000, 28, 28)
	 Sample Data : aml://artifactId/ExperimentRun/dcid.f3c995c8-bc6e-40f2-84a6-0e48a8948446/Sample Data_1609858333.png


Assuming the pipeline was successful, a new model should be registered with a *Training context* tag indicating it was trained in a pipeline. Run the following code to verify this.

In [31]:
from azureml.core import Model

for model in Model.list(ws):
    print(model.name, 'version:', model.version)
    for tag_name in model.tags:
        tag = model.tags[tag_name]
        print ('\t',tag_name, ':', tag)
    for prop_name in model.properties:
        prop = model.properties[prop_name]
        print ('\t',prop_name, ':', prop)
    print('\n')

fashion_mnist_model version: 2
	 Training context : Pipeline
	 Test Loss : 0.25535974576473236
	 Test Accuracy : 0.9074


fashion_mnist_model version: 1
	 Training context : Pipeline
	 Test Loss : 0.2552644387125969
	 Test Accuracy : 0.9058


diabetes_model version: 1
	 Training context : Pipeline
	 AUC : 0.8831150388293764
	 Accuracy : 0.8991111111111111




## Publish the pipeline

After you've created and tested a pipeline, you can publish it as a REST service.

In [33]:
# Publish the pipeline from the run
published_pipeline = pipeline_run.publish_pipeline(
    name="fashion-training-pipeline", description="Train fashion mnist model", version="2.0")

published_pipeline

Pipeline(Name: fashion-training-pipeline,
Id: 8f3c5018-5bbb-4384-a9fa-cb6c5f93b47f,
Status: Active,
Endpoint: https://westeurope.api.azureml.ms/pipelines/v1.0/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourceGroups/cloud-native-ml/providers/Microsoft.MachineLearningServices/workspaces/cloudnativeml/PipelineRuns/PipelineSubmit/8f3c5018-5bbb-4384-a9fa-cb6c5f93b47f)

Note that the published pipeline has an endpoint, which you can see in the **Endpoints** page (on the **Pipeline Endpoints** tab) in [Azure Machine Learning studio](https://ml.azure.com). You can also find its URI as a property of the published pipeline object:

In [34]:
rest_endpoint = published_pipeline.endpoint
print(rest_endpoint)

https://westeurope.api.azureml.ms/pipelines/v1.0/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourceGroups/cloud-native-ml/providers/Microsoft.MachineLearningServices/workspaces/cloudnativeml/PipelineRuns/PipelineSubmit/8f3c5018-5bbb-4384-a9fa-cb6c5f93b47f


## Call the pipeline endpoint

To use the endpoint, client applications need to make a REST call over HTTP. This request must be authenticated, so an authorization header is required. A real application would require a service principal with which to be authenticated, but to test this out, we'll use the authorization header from your current connection to your Azure workspace, which you can get using the following code:

In [35]:
from azureml.core.authentication import InteractiveLoginAuthentication

interactive_auth = InteractiveLoginAuthentication()
auth_header = interactive_auth.get_authentication_header()
print("Authentication header ready.")

Authentication header ready.


Now we're ready to call the REST interface. The pipeline runs asynchronously, so we'll get an identifier back, which we can use to track the pipeline experiment as it runs:

In [36]:
import requests

experiment_name = 'published-fashion-pipeline'

rest_endpoint = published_pipeline.endpoint
response = requests.post(rest_endpoint, 
                         headers=auth_header, 
                         json={"ExperimentName": experiment_name})
run_id = response.json()["Id"]
run_id

'c17e8b6a-cc84-4bb4-999f-648fb9746753'

Since you have the run ID, you can use it to wait for the run to complete.

> **Note**: The pipeline should complete quickly, because each step was configured to allow output reuse. This was done primarily for convenience and to save time in this course. In reality, you'd likely want the first step to run every time in case the data has changed, and trigger the subsequent steps only if the output from step one changes.

In [17]:
from azureml.pipeline.core.run import PipelineRun

published_pipeline_run = PipelineRun(ws.experiments[experiment_name], run_id)
pipeline_run.wait_for_completion(show_output=True)

PipelineRunId: 8be396f1-a042-4796-a18f-b688d5165e17
Link to Azure Machine Learning Portal: https://ml.azure.com/experiments/mslearn-diabetes-pipeline/runs/8be396f1-a042-4796-a18f-b688d5165e17?wsid=/subscriptions/a2a1fc9f-5671-4479-8922-ad16e34c0fdc/resourcegroups/cloud-native-ml/workspaces/cloudnativeml

PipelineRun Execution Summary
PipelineRun Status: Finished
{'runId': '8be396f1-a042-4796-a18f-b688d5165e17', 'status': 'Completed', 'startTimeUtc': '2021-01-04T11:46:21.553326Z', 'endTimeUtc': '2021-01-04T12:01:55.066566Z', 'properties': {'azureml.runsource': 'azureml.PipelineRun', 'runSource': 'SDK', 'runType': 'SDK', 'azureml.parameters': '{}'}, 'inputDatasets': [], 'outputDatasets': [], 'logFiles': {'logs/azureml/executionlogs.txt': 'https://cloudnativeml8223825908.blob.core.windows.net/azureml/ExperimentRun/dcid.8be396f1-a042-4796-a18f-b688d5165e17/logs/azureml/executionlogs.txt?sv=2019-02-02&sr=b&sig=MwZFRyd%2FHuyytBi7hK3RYOEd3BdCgXyX6Sg4376RdSQ%3D&st=2021-01-04T11%3A36%3A45Z&se=2

'Finished'

## Schedule the Pipeline

Suppose the clinic for the diabetes patients collects new data each week, and adds it to the dataset. You could run the pipeline every week to retrain the model with the new data.

In [ ]:
from azureml.pipeline.core import ScheduleRecurrence, Schedule

# Submit the Pipeline every Monday at 00:00 UTC
recurrence = ScheduleRecurrence(frequency="Week", interval=1, week_days=["Monday"], time_of_day="00:00")
weekly_schedule = Schedule.create(ws, name="weekly-diabetes-training", 
                                  description="Based on time",
                                  pipeline_id=published_pipeline.id, 
                                  experiment_name='mslearn-diabetes-pipeline', 
                                  recurrence=recurrence)
print('Pipeline scheduled.')

You can retrieve the schedules that are defined in the workspace like this:

In [ ]:
schedules = Schedule.list(ws)
schedules

You can check the latest run like this:

In [ ]:
pipeline_experiment = ws.experiments.get('mslearn-diabetes-pipeline')
latest_run = list(pipeline_experiment.get_runs())[0]

latest_run.get_details()

This is a simple example, designed to demonstrate the principle. In reality, you could build more sophisticated logic into the pipeline steps - for example, evaluating the model against some test data to calculate a performance metric like AUC or accuracy, comparing the metric to that of any previously registered versions of the model, and only registering the new model if it performs better.

You can use the [Azure Machine Learning extension for Azure DevOps](https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.vss-services-azureml) to combine Azure ML pipelines with Azure DevOps pipelines (yes, it *is* confusing that they have the same name!) and integrate model retraining into a *continuous integration/continuous deployment (CI/CD)* process. For example you could use an Azure DevOps *build* pipeline to trigger an Azure ML pipeline that trains and registers a model, and when the model is registered it could trigger an Azure Devops *release* pipeline that deploys the model as a web service, along with the application or service that consumes the model.